# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ansibleplaybook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible jmespath dnspython
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install ansible plugins from ansible-galaxy
      run: |
        ansible-galaxy install hemanth22.gitconfig
        ansible-galaxy collection install ansible.utils
        ansible-galaxy collection install ansible.netcommon
        ansible-galaxy collection install community.general
    - name: pip modules list
      run: |
        pip list
        python -V
        pip -V
        ls -ltra
        pwd
    - name: test ansible playbooks
      run: |
        echo "Basic Verion"
        ansible-playbook -i inventory jsonparser.playbook
        echo "Version 2"
        ansible-playbook -i inventory jsonparser_backup.playbook
        echo "Version 3"
        ansible-playbook -i inventory jsonparser_backup_1.playbook
        ls -ltra
        pwd
